processes:
  - name: 'Laser Welding'
    params:
      - name: 'power (W)'
        min: 900
        max: 1200
        step: 1
      - name: 'welding speed (m/min)'
        min: 0.8
        max: 1.2
        step: 0.1
      - name: 'gas flow rate (l/min)'
        min: 10
        max: 20
        step: 1
      - name: 'focal position (mm)'
        min: -2
        max: 2
        step: 1
      - name: 'angular position (°)'
        min: -15
        max: 15
        step: 1
      - name: 'material thickness (mm)'
        min: 0.5
        max: 0.7
        step: 0.1
  - name: 'Self Adapting'